apiVersion: v1
kind: Namespace
metadata:
  name: micro_service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  name: micro_service
spec:
  revisionHistoryLimit: 10
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      name: webap-ppod
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp-container
          image: deepakshipurushotham/srs_micro_service:13
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: webappsvc
  name: micro_service
spec:
  selector:
    app: webapp
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080